% =========================================================================
% RUN THE SIMULATION
% input:    kgrid
%           pulse
%           medium
%           source
%           sensor
% output:   sensor_data
%
% Compute sensor data of waves generated by oscillating microbubbles in a
% homogeneous medium. Nonlinear propagation is neglected.
%
% Optimized: precomputes frequency-domain quantities once, batch FFTs.
%
% =========================================================================
function sensor_data = run_simulation_homogeneous(...
    run_param, kgrid, medium, source, sensor)

% Compute the average properties of the medium (homogeneous medium
% approximation):
medium = average_medium(medium);

N_source    = size(source.points,1);   	% Number of sources
N_sensor    = size(sensor.points,1);   	% Number of sensors

Fs = 1/kgrid.dt;
useGPU = strcmp(run_param.DATA_CAST,'gpuArray-single') || ...
         strcmp(run_param.DATA_CAST,'gpuArray-double');

% Preallocate sensor data:
dataType = class(source.mass_source); % 'single' or 'double'
if useGPU
    disp(['Selected and reset GPU device ' ...
        num2str(run_param.DEVICE_NUM) '.']);
    gpuDevice(run_param.DEVICE_NUM + 1);
    sensor_data.p      = gpuArray(zeros(N_sensor,kgrid.Nt, dataType));
    source.mass_source = gpuArray(source.mass_source);
else
    sensor_data.p = zeros(N_sensor,kgrid.Nt, dataType);
end

%% Precompute all mass source derivatives in batch (single matrix FFT)
N_ms = size(source.mass_source, 2);
f_ms = cast((0:(N_ms-1))/N_ms*Fs, dataType);
f_ms(ceil(N_ms/2+1):N_ms) = -f_ms(floor(1+N_ms/2):-1:2);

% Batch derivative: d/dt via frequency-domain multiplication
if useGPU
    jw = gpuArray(2i*pi*cast(f_ms, dataType));
else
    jw = 2i*pi*cast(f_ms, dataType);
end
MS_dot_all = real(ifft(jw .* fft(source.mass_source, [], 2), [], 2));

% Trim/pad to kgrid.Nt
if N_ms < kgrid.Nt
    MS_dot_all(:, (N_ms+1):kgrid.Nt) = 0;
elseif N_ms > kgrid.Nt
    MS_dot_all = MS_dot_all(:, 1:kgrid.Nt);
end

%% Precompute frequency-domain attenuation and dispersion (ONCE for all sources)
N_ext = kgrid.Nt * 2;  % domain extension to prevent periodic wrapping
f_ext = cast((0:(N_ext-1))/N_ext*Fs, dataType);

% Attenuation
a_coeff = medium.a * log(10) * 100 / 20;
f_MHz = f_ext / 1e6;
alpha_f = cast(a_coeff * abs(f_MHz).^medium.b, dataType);

% Dispersion
if isfield(medium,'alpha_mode') && strcmp(medium.alpha_mode, 'no_dispersion')
    f_over_c = cast(f_ext / medium.c, dataType);
else
    c_disp = powerLawKramersKronig(2*pi*double(f_ext), 0, medium.c, ...
        db2neper(medium.a, medium.b), medium.b);
    f_over_c = cast(f_ext ./ c_disp, dataType);
end

if useGPU
    alpha_f   = gpuArray(alpha_f);
    f_over_c  = gpuArray(f_over_c);
end

% Precompute FFTs of all mass source derivatives (batch)
MS_dot_fft = fft(MS_dot_all, N_ext, 2);  % [N_source x N_ext]

%% Propagation loop (still per-source due to varying distances)
fprintf('Propagating %d sources ...', N_source);
for m = 1:N_source

    % Compute the distance between source m and the sensor points:
    d0 = vecnorm(sensor.points-source.points(m,:),2,2);

    if run_param.gridded
        % Map values of d on a grid to reduce computation time:
        [d, i_sampled] = gridded_distance(d0, kgrid.dt*medium.c);
    else
        d = d0;
    end

    % Convert to requested data type:
    if useGPU
        d = gpuArray(cast(d,dataType));
    else
        d = cast(d,dataType);
    end

    % Compute transfer function for this source's distances
    W = exp(-d * alpha_f - 2i*pi * d * f_over_c);
    W(:,ceil(N_ext/2+1):N_ext) = conj(W(:,floor(1+N_ext/2):-1:2));

    % Apply Green's function with pre-computed FFT
    d_safe = d;
    d_safe(d0 == 0) = Inf;
    p = real(ifft(MS_dot_fft(m,:) ./ (4*pi*d_safe) .* W, [], 2));
    p = p(:, 1:N_ext/2);

    % Prevent sources from self-sensing:
    p(d0 == 0,:) = 0;

    % Add the sensed echo to the sensor data:
    if run_param.gridded
        sensor_data.p = sensor_data.p + p(i_sampled,:);
    else
        sensor_data.p = sensor_data.p + p;
    end

end
fprintf(' done.\n');

end


function medium_average = average_medium(medium)
% Compute the average value of medium properties.

medium_average.rho = mean(medium.density,     'all');
medium_average.c   = mean(medium.sound_speed, 'all');
medium_average.a   = mean(medium.alpha_coeff, 'all');
medium_average.b   = mean(medium.alpha_power, 'all');

if isfield(medium,'alpha_mode')
    medium_average.alpha_mode = medium.alpha_mode;
end

end

function [d_grid, i_grid] = gridded_distance(d, dx)
% Snap values in array d to a grid d_grid with step size dx.
% Grid is set up with respect to mean of d.
% The indices i_grid are defined such that d_grid(i_grid(n)) is the element
% closest to d(n).

    % Set up grid:
    i_grid = round((d - mean(d))/dx);
    d_grid = (min(i_grid):max(i_grid))*dx + mean(d);
    d_grid = transpose(d_grid);

    % Return indices of grid corresponding to elements in d:
    i_mean = -min(i_grid) + 1;
    i_grid = i_grid + i_mean;

end
