% =========================================================================
% RUN THE SIMULATION
% input:    kgrid
%           pulse
%           medium
%           source
%           sensor
% output:   sensor_data
%
% Compute sensor data of waves generated by oscillating microbubbles in a
% homogeneous medium. Nonlinear propagation is neglected.
%
% Optimized: precomputes frequency-domain quantities once, batch FFTs.
%
% =========================================================================
function sensor_data = run_simulation_homogeneous(...
    run_param, kgrid, medium, source, sensor)

% Compute the average properties of the medium (homogeneous medium
% approximation):
medium = average_medium(medium);

N_source    = size(source.points,1);   	% Number of sources
N_sensor    = size(sensor.points,1);   	% Number of sensors

Fs = 1/kgrid.dt;
useGPU = strcmp(run_param.DATA_CAST,'gpuArray-single') || ...
         strcmp(run_param.DATA_CAST,'gpuArray-double');

% Preallocate sensor data:
%
% The accumulator is one row per sensor and one column per sample, and on
% the GPU that is a single gpuArray -- which MATLAB caps at intmax('int32')
% elements regardless of free device memory. v7's grid needed 1.06e9 and
% fitted; v10's lambda/8 grid needs 2.52e9 and failed at this line before
% frame 1. Holding it as a list of sensor chunks keeps every array under the
% limit. Nothing about the physics changes: sensor rows are independent, and
% the per-source work that dominates the loop is done over the distance
% grid, which the split does not touch.
dataType = class(source.mass_source); % 'single' or 'double'
if isfield(run_param, 'SensorChunkElements')
    chunkLimit = run_param.SensorChunkElements;   % tests only
else
    chunkLimit = [];
end
[chunk_first, chunk_last] = sensor_chunk_bounds( ...
    N_sensor, kgrid.Nt, useGPU, chunkLimit);
N_chunk = numel(chunk_first);
if N_chunk > 1
    run_log('banner', 'sensorchunks', ...
        ['Sensor axis split into %d chunks of <=%d points: ' ...
         '%d x %d exceeds the %d-element gpuArray limit'], ...
        N_chunk, max(chunk_last - chunk_first + 1), ...
        N_sensor, kgrid.Nt, intmax('int32'));
end

sensor_p = cell(1, N_chunk);
if useGPU
    run_log('banner', 'gpudevice', ...
        'k-Wave GPU device %s selected and reset', ...
        num2str(run_param.DEVICE_NUM));
    gpuDevice(run_param.DEVICE_NUM + 1);
    for c = 1:N_chunk
        sensor_p{c} = gpuArray(zeros( ...
            chunk_last(c) - chunk_first(c) + 1, kgrid.Nt, dataType));
    end
    source.mass_source = gpuArray(source.mass_source);
else
    for c = 1:N_chunk
        sensor_p{c} = zeros( ...
            chunk_last(c) - chunk_first(c) + 1, kgrid.Nt, dataType);
    end
end

%% Precompute all mass source derivatives in batch (single matrix FFT)
N_ms = size(source.mass_source, 2);
f_ms = cast((0:(N_ms-1))/N_ms*Fs, dataType);
f_ms(ceil(N_ms/2+1):N_ms) = -f_ms(floor(1+N_ms/2):-1:2);

% Batch derivative: d/dt via frequency-domain multiplication
if useGPU
    jw = gpuArray(2i*pi*cast(f_ms, dataType));
else
    jw = 2i*pi*cast(f_ms, dataType);
end
MS_dot_all = real(ifft(jw .* fft(source.mass_source, [], 2), [], 2));

% Trim/pad to kgrid.Nt
if N_ms < kgrid.Nt
    MS_dot_all(:, (N_ms+1):kgrid.Nt) = 0;
elseif N_ms > kgrid.Nt
    MS_dot_all = MS_dot_all(:, 1:kgrid.Nt);
end

%% Precompute frequency-domain attenuation and dispersion (ONCE for all sources)
N_ext = kgrid.Nt * 2;  % domain extension to prevent periodic wrapping
f_ext = cast((0:(N_ext-1))/N_ext*Fs, dataType);

% Attenuation
a_coeff = medium.a * log(10) * 100 / 20;
f_MHz = f_ext / 1e6;
alpha_f = cast(a_coeff * abs(f_MHz).^medium.b, dataType);

% Dispersion
if isfield(medium,'alpha_mode') && strcmp(medium.alpha_mode, 'no_dispersion')
    f_over_c = cast(f_ext / medium.c, dataType);
else
    c_disp = powerLawKramersKronig(2*pi*double(f_ext), 0, medium.c, ...
        db2neper(medium.a, medium.b), medium.b);
    f_over_c = cast(f_ext ./ c_disp, dataType);
end

if useGPU
    alpha_f   = gpuArray(alpha_f);
    f_over_c  = gpuArray(f_over_c);
end

% Precompute FFTs of all mass source derivatives (batch)
MS_dot_fft = fft(MS_dot_all, N_ext, 2);  % [N_source x N_ext]

%% Propagation loop (still per-source due to varying distances)
% The loop is 39% of a frame and mixes work of very different kinds: CPU
% distance arithmetic and a host-to-device transfer, a large complex
% exponential and inverse transform on the GPU, and an expansion from the
% distance grid back to every sensor point. profilePropagation splits them
% apart; see stage_toc for why it is not free.
profilePropagation = isfield(run_param, 'ProfilePropagation') && ...
    run_param.ProfilePropagation;

for m = 1:N_source

    t_dist = stage_tic(profilePropagation);

    % Compute the distance between source m and the sensor points:
    d0 = vecnorm(sensor.points-source.points(m,:),2,2);

    if run_param.gridded
        % Map values of d on a grid to reduce computation time:
        [d, i_sampled] = gridded_distance(d0, kgrid.dt*medium.c);
    else
        d = d0;
    end

    % Convert to requested data type:
    if useGPU
        d = gpuArray(cast(d,dataType));
    else
        d = cast(d,dataType);
    end

    stage_toc(profilePropagation, 'dist', t_dist, useGPU);
    t_field = stage_tic(profilePropagation);

    % Compute transfer function for this source's distances
    W = exp(-d * alpha_f - 2i*pi * d * f_over_c);
    W(:,ceil(N_ext/2+1):N_ext) = conj(W(:,floor(1+N_ext/2):-1:2));

    % Apply Green's function with pre-computed FFT.
    %
    % Mask d on its own zeros, as upstream's calc_scatter_attenuated did with
    % r(r==0) = Inf. Masking it with d0's zeros instead is a length mismatch
    % whenever run_param.gridded is set: d then holds one entry per
    % distance-grid point and d0 one per sensor.
    d_safe = d;
    d_safe(d == 0) = Inf;
    p = real(ifft(MS_dot_fft(m,:) ./ (4*pi*d_safe) .* W, [], 2));
    p = p(:, 1:N_ext/2);

    stage_toc(profilePropagation, 'field', t_field, useGPU);
    t_accum = stage_tic(profilePropagation);

    % Expand the distance grid back to sensor points before suppressing
    % self-sensing: only then is a row a sensor, which is what d0 indexes.
    % One chunk at a time, so the expanded block is allocatable even when the
    % whole accumulator would not be.
    for c = 1:N_chunk
        rows = chunk_first(c):chunk_last(c);
        if run_param.gridded
            p_sensor = p(i_sampled(rows),:);
        else
            p_sensor = p(rows,:);
        end
        p_sensor(d0(rows) == 0,:) = 0;
        sensor_p{c} = sensor_p{c} + p_sensor;
    end

    stage_toc(profilePropagation, 'accum', t_accum, useGPU);

end

% Join the chunks. With more than one chunk the joined array is over the
% device limit by construction, so it is only ever assembled on the host;
% each chunk is released as it lands to keep the peak at one copy.
if N_chunk == 1
    sensor_data.p = sensor_p{1};
else
    sensor_data.p = zeros(N_sensor, kgrid.Nt, dataType);
    for c = 1:N_chunk
        sensor_data.p(chunk_first(c):chunk_last(c), :) = gather(sensor_p{c});
        sensor_p{c} = [];
    end
end

end


function t = stage_tic(profilePropagation)
% A timer only when the breakdown was asked for.

if profilePropagation
    t = tic;
else
    t = [];
end

end


function stage_toc(profilePropagation, name, t, useGPU)
% Record one propagation sub-stage.
%
% gpuArray operations are queued, so toc alone would report how long it
% took to submit the work rather than to do it, and every stage but the
% last would look free. wait() makes the number honest at the cost of
% serialising the loop, which is why the whole breakdown is opt-in.

if ~profilePropagation
    return
end
if useGPU
    wait(gpuDevice);
end
run_log('stage', name, toc(t));

end


function medium_average = average_medium(medium)
% Compute the average value of medium properties.

medium_average.rho = mean(medium.density,     'all');
medium_average.c   = mean(medium.sound_speed, 'all');
medium_average.a   = mean(medium.alpha_coeff, 'all');
medium_average.b   = mean(medium.alpha_power, 'all');

if isfield(medium,'alpha_mode')
    medium_average.alpha_mode = medium.alpha_mode;
end

end

function [d_grid, i_grid] = gridded_distance(d, dx)
% Snap values in array d to a grid d_grid with step size dx.
% Grid is set up with respect to mean of d.
% The indices i_grid are defined such that d_grid(i_grid(n)) is the element
% closest to d(n).

    % Set up grid:
    i_grid = round((d - mean(d))/dx);
    d_grid = (min(i_grid):max(i_grid))*dx + mean(d);
    d_grid = transpose(d_grid);

    % Return indices of grid corresponding to elements in d:
    i_mean = -min(i_grid) + 1;
    i_grid = i_grid + i_mean;

end
